[phases.install]
cmds = ["yarn install --frozen-lockfile"]
cacheDirectories = ["node_modules/.cache"]

[phases.build]
dependsOn = ["install"]
cmds = ["yarn build"]
cacheDirectories = [".next/cache"]

[start]
cmd = "yarn start"
